image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t emnagaidi/flask-app:$CI_COMMIT_SHORT_SHA .
    - docker push emnagaidi/flask-app:$CI_COMMIT_SHORT_SHA
  only:
    - main

deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y curl
    - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    - kubectl set image deployment/flask-app flask-app=emnagaidi/flask-app:$CI_COMMIT_SHORT_SHA
  only:
    - main
